<a href="https://colab.research.google.com/github/agarwaljubin/loops-/blob/main/working_with_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd

In [8]:
path="/content/drive/MyDrive/data sets/services.csv"

In [9]:
df=pd.read_csv(path)

In [10]:
df.head()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN
3,4,4,NaN,NaN,NaN,Apply by phone.,"Parents, children, families with problems of c...",Provides supervised visitation services and a ...,NaN,NaN,...,NaN,"INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...",NaN,Family Visitation Center,NaN,San Mateo County,active,No wait.,NaN,NaN
4,5,5,NaN,NaN,NaN,Phone for information.,Low-income working families with children tran...,Provides fixed 8% short term loans to eligible...,Eligibility: Low-income family with legal cust...,NaN,...,NaN,"COMMUNITY SERVICES, Speakers, Automobile Loans",NaN,Economic Self-Sufficiency Program,NaN,San Mateo County,active,NaN,NaN,NaN

In [11]:
df.head(3)

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
0,1,1,NaN,NaN,NaN,Walk in or apply by phone.,"Older adults age 55 or over, ethnic minorities...",A walk-in center for older adults that provide...,"Age 55 or over for most programs, age 60 or ov...",NaN,...,NaN,"ADULT PROTECTION AND CARE SERVICES, Meal Sites...",NaN,Fair Oaks Adult Activity Center,NaN,Colma,active,No wait.,NaN,NaN
1,2,2,NaN,NaN,NaN,Apply by phone for an appointment.,Residents of San Mateo County age 55 or over,Provides training and job placement to eligibl...,"Age 55 or over, county resident and willing an...",NaN,...,NaN,"EMPLOYMENT/TRAINING SERVICES, Job Development,...",NaN,Second Career Employment Program,NaN,San Mateo County,active,Varies.,NaN,NaN
2,3,3,NaN,NaN,NaN,Phone for information (403-4300 Ext. 4322).,Older adults age 55 or over who can benefit fr...,Offers supportive counseling services to San M...,Resident of San Mateo County age 55 or over,NaN,...,NaN,"Geriatric Counseling, Older Adults, Gay, Lesbi...",NaN,Senior Peer Counseling,NaN,San Mateo County,active,Varies.,NaN,NaN

In [12]:
df.tail()

,id,location_id,program_id,accepted_payments,alternate_name,application_process,audience,description,eligibility,email,...,interpretation_services,keywords,languages,name,required_documents,service_areas,status,wait_time,website,taxonomy_ids
18,19,19,NaN,NaN,NaN,Call for screening appointment (650-347-3648).,NaN,Provides free medical and dental care to those...,Low-income person without access to health care,NaN,...,NaN,"HEALTH SERVICES, Outpatient Care, Community Cl...",NaN,San Mateo Free Medical Clinic,NaN,"Belmont, Burlingame",active,Varies.,NaN,NaN
19,20,20,NaN,NaN,NaN,Walk in.,NaN,no unrequired fields for this service,NaN,NaN,...,NaN,NaN,NaN,Service with blank fields,NaN,NaN,defunct,NaN,NaN,NaN
20,21,21,NaN,NaN,NaN,By phone during business hours.,NaN,just a test service,NaN,NaN,...,NaN,NaN,NaN,Service for Admin Test Location,NaN,San Mateo County,inactive,NaN,NaN,NaN
21,22,22,NaN,"Cash, Check, Credit Card",Fotos para pasaportes,Walk in or apply by phone or mail,"Profit and nonprofit businesses, the public, m...",[NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...,NaN,passports@example.org,...,We offer 3-way interpretation services over th...,"Salud, Medicina",Spanish,Passport Photos,Government-issued picture identification,"Alameda County, San Mateo County",active,No wait to 2 weeks.,http://www.example.com,"105, 108, 108-05, 108-05-01, 111, 111-05"
22,23,22,NaN,NaN,NaN,Walk in or apply by phone or mail,"Second service and nonprofit businesses, the p...",[NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...,NaN,NaN,...,NaN,"Ruby on Rails/Postgres/Redis, testing, wic",NaN,Example Service Name,NaN,"San Mateo County, Alameda County",active,No wait to 2 weeks,http://www.example.com,NaN

In [13]:
type(df)

pandas.core.frame.DataFrame

In [14]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [15]:
type(df)

pandas.core.frame.DataFrame

In [16]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [17]:
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [18]:
df["service_areas"]

0                                     Colma
1                          San Mateo County
2                          San Mateo County
3                          San Mateo County
4                          San Mateo County
5                          San Mateo County
6       Belmont, Burlingame, East Palo Alto
7                   Belmont, East Palo Alto
8                          San Mateo County
9                          San Mateo County
10                         San Mateo County
11                                Daly City
12                         San Mateo County
13      Belmont, Burlingame, East Palo Alto
14         Alameda County, San Mateo County
15                                      NaN
16    Colma, Daly City, South San Francisco
17                           East Palo Alto
18                      Belmont, Burlingame
19                                      NaN
20                         San Mateo County
21         Alameda County, San Mateo County
22         San Mateo County, Alameda County
Name: service_areas, dtype: object

In [19]:
df["website"]

0                        NaN
1                        NaN
2                        NaN
3                        NaN
4                        NaN
5                        NaN
6                        NaN
7                        NaN
8                        NaN
9                        NaN
10                       NaN
11                       NaN
12                       NaN
13                       NaN
14                       NaN
15                       NaN
16                       NaN
17                       NaN
18                       NaN
19                       NaN
20                       NaN
21    http://www.example.com
22    http://www.example.com
Name: website, dtype: object

In [20]:
df["status"]

0       active
1       active
2       active
3       active
4       active
5       active
6       active
7       active
8       active
9       active
10      active
11      active
12      active
13      active
14      active
15      active
16      active
17      active
18      active
19     defunct
20    inactive
21      active
22      active
Name: status, dtype: object

In [21]:
type(df["status"])

pandas.core.series.Series

In [24]:
list((df["status"]))

['active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'active',
 'defunct',
 'inactive',
 'active',
 'active']

In [25]:
df[["status"]]

      status
0     active
1     active
2     active
3     active
4     active
5     active
6     active
7     active
8     active
9     active
10    active
11    active
12    active
13    active
14    active
15    active
16    active
17    active
18    active
19   defunct
20  inactive
21    active
22    active

In [26]:
type(df[["status"]])

pandas.core.frame.DataFrame

In [27]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [30]:
df[["email","keywords"]]

                    email                                           keywords
0                     NaN  ADULT PROTECTION AND CARE SERVICES, Meal Sites...
1                     NaN  EMPLOYMENT/TRAINING SERVICES, Job Development,...
2                     NaN  Geriatric Counseling, Older Adults, Gay, Lesbi...
3                     NaN  INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...
4                     NaN     COMMUNITY SERVICES, Speakers, Automobile Loans
5                     NaN  ADULT PROTECTION AND CARE SERVICES, In-Home Su...
6                     NaN  ADULT PROTECTION AND CARE SERVICES, Adult Day ...
7                     NaN  ADULT PROTECTION AND CARE SERVICES, Meal Sites...
8                     NaN  EDUCATION SERVICES, Library, Libraries, Public...
9                     NaN  EDUCATION SERVICES, Library, Libraries, Public...
10                    NaN  EDUCATION SERVICES, Library, Libraries, Public...
11                    NaN  EDUCATION SERVICES, Adult, Alternative, Litera...
12                    NaN  EDUCATION SERVICES, Library, Libraries, Public...
13                    NaN  COMMUNITY SERVICES, Interpretation/Translation...
14                    NaN  ALCOHOLISM SERVICES, Residential Care, DRUG AB...
15                    NaN  COMMODITY SERVICES, Clothing/Personal Items, C...
16                    NaN  COMMODITY SERVICES, Clothing/Personal Items, C...
17                    NaN  HEALTH SERVICES, Outpatient Care, Community Cl...
18                    NaN  HEALTH SERVICES, Outpatient Care, Community Cl...
19                    NaN                                                NaN
20                    NaN                                                NaN
21  passports@example.org                                    Salud, Medicina
22                    NaN         Ruby on Rails/Postgres/Redis, testing, wic

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('email').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

In [31]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [35]:
df1=pd.read_excel("/content/drive/MyDrive/data sets/LUSID Excel - Setting up your market data.xlsx")

In [36]:
type(df1)

pandas.core.frame.DataFrame

In [38]:
df1.dtypes

Unnamed: 0    float64
Unnamed: 1    float64
Unnamed: 2    float64
Unnamed: 3     object
Unnamed: 4     object
Unnamed: 5     object
Unnamed: 6    float64
Unnamed: 7     object
Unnamed: 8     object
Unnamed: 9     object
dtype: object

In [39]:
df1.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

In [40]:
df1[['Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8']]

,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,NaN,NaN
1,NaN,NaN,NaN
2,NaN,NaN,NaN
3,NaN,NaN,NaN
4,NaN,NaN,NaN
5,NaN,NaN,NaN
6,NaN,NaN,NaN
7,NaN,NaN,NaN
8,NaN,NaN,NaN
9,NaN,NaN,NaN
10,NaN,NaN,NaN
11,NaN,"LUSID also accepts UTC, UTS offsets and cutlabels",NaN
12,NaN,NaN,NaN
13,NaN,Additional formats,NaN
14,NaN,NaN,NaN
15,NaN,Standard UTC timestamp:,"""YYYY-MM-DDTHH:MM:SS.00Z"""
16,NaN,NaN,NaN
17,NaN,Convert date into a string,2019-04-10T 13:30:45.55Z
18,NaN,NaN,NaN
19,NaN,UTC offset (not recognised as an excel date),2019-04-10T13:30:45+04:00
20,NaN,NaN,NaN
21,NaN,Cutlabel,2019-04-10NSingaporeClose
22,NaN,NaN,NaN
23,NaN,NaN,NaN
24,NaN,NaN,NaN
25,NaN,NaN,NaN
26,NaN,NaN,NaN
27,NaN,NaN,NaN

In [41]:
pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html")

[        Rk             Player   Age Team  Pos     G    GS      MP     FG  \
 0      1.0       James Harden  25.0  HOU   SG  81.0  81.0  2981.0  647.0
 1      2.0      Stephen Curry  26.0  GSW   PG  80.0  80.0  2613.0  653.0
 2      3.0  Russell Westbrook  26.0  OKC   PG  67.0  67.0  2302.0  627.0
 3      4.0       LeBron James  30.0  CLE   SF  69.0  69.0  2493.0  624.0
 4      5.0     Damian Lillard  24.0  POR   PG  82.0  82.0  2925.0  590.0
 ..     ...                ...   ...  ...  ...   ...   ...     ...    ...
 647  489.0        Malcolm Lee  24.0  PHI   SG   1.0   0.0     2.0    0.0
 648  490.0        Kalin Lucas  25.0  MEM   PG   1.0   0.0     6.0    0.0
 649  491.0       Ronny Turiaf  32.0  MIN    C   2.0   0.0    19.0    0.0
 650  492.0         David Wear  24.0  SAC   PF   2.0   0.0     7.0    0.0
 651    NaN     League Average   NaN  NaN  NaN   NaN   NaN     NaN    NaN

         FGA  ...    DRB    TRB    AST    STL   BLK    TOV     PF     PTS  \
 0    1470.0  ...  384.0  459.0  565.0  154.0  60.0  321.0  208.0  2217.0
 1    1341.0  ...  285.0  341.0  619.0  163.0  16.0  249.0  158.0  1900.0
 2    1471.0  ...  364.0  488.0  574.0  140.0  14.0  293.0  184.0  1886.0
 3    1279.0  ...  365.0  416.0  511.0  109.0  49.0  272.0  135.0  1743.0
 4    1360.0  ...  329.0  378.0  507.0   97.0  21.0  222.0  164.0  1720.0
 ..      ...  ...    ...    ...    ...    ...   ...    ...    ...     ...
 647     1.0  ...    0.0    0.0    0.0    0.0   0.0    0.0    0.0     0.0
 648     1.0  ...    0.0    0.0    0.0    1.0   0.0    0.0    1.0     0.0
 649     0.0  ...    1.0    1.0    2.0    0.0   0.0    0.0    0.0     0.0
 650     2.0  ...    0.0    2.0    1.0    0.0   0.0    0.0    1.0     0.0
 651     NaN  ...    NaN    NaN    NaN    NaN   NaN    NaN    NaN     NaN

      Trp-Dbl                 Awards
 0        4.0          MVP-2,AS,NBA1
 1        0.0          MVP-1,AS,NBA1
 2       11.0          MVP-4,AS,NBA2
 3        2.0  MVP-3,DPOY-13,AS,NBA1
 4        0.0                     AS
 ..       ...                    ...
 647      0.0                    NaN
 648      0.0                    NaN
 649      0.0                    NaN
 650      0.0                    NaN
 651      NaN                    NaN

 [652 rows x 32 columns],
         Rk           Player   Age Team  Pos     G    GS     MP     FG    FGA  \
 0      1.0     LeBron James  30.0  CLE   SF  20.0  20.0  844.0  227.0  544.0
 1      2.0    Stephen Curry  26.0  GSW   PG  21.0  21.0  826.0  200.0  439.0
 2      3.0     James Harden  25.0  HOU   SG  17.0  17.0  636.0  129.0  294.0
 3      4.0    Klay Thompson  24.0  GSW   SG  21.0  21.0  761.0  149.0  334.0
 4      5.0    Blake Griffin  25.0  LAC   PF  14.0  14.0  557.0  140.0  274.0
 ..     ...              ...   ...  ...  ...   ...   ...    ...    ...    ...
 204  205.0       Greg Smith  24.0  DAL   PF   1.0   0.0    1.0    0.0    0.0
 205  206.0       Russ Smith  23.0  MEM   PG   2.0   0.0    3.0    0.0    0.0
 206  207.0  Mirza Teletović  29.0  BRK   PF   3.0   0.0   16.0    0.0    5.0
 207  208.0   Gerald Wallace  32.0  BOS   SF   1.0   0.0    4.0    0.0    1.0
 208    NaN   League Average   NaN  NaN  NaN   NaN   NaN    NaN    NaN    NaN

      ...    DRB    TRB    AST   STL   BLK   TOV    PF    PTS  Trp-Dbl  Awards
 0    ...  189.0  226.0  169.0  33.0  21.0  82.0  58.0  601.0      3.0     NaN
 1    ...   85.0  105.0  134.0  39.0   3.0  82.0  47.0  594.0      0.0     NaN
 2    ...   85.0   97.0  128.0  28.0   7.0  77.0  49.0  462.0      1.0     NaN
 3    ...   72.0   81.0   54.0  16.0  19.0  41.0  64.0  391.0      0.0     NaN
 4    ...  140.0  178.0   86.0  14.0  14.0  45.0  43.0  357.0      3.0     NaN
 ..   ...    ...    ...    ...   ...   ...   ...   ...    ...      ...     ...
 204  ...    0.0    0.0    0.0   0.0   0.0   0.0   0.0    0.0      0.0     NaN
 205  ...    0.0    0.0    2.0   0.0   0.0   0.0   0.0    0.0      0.0     NaN
 206  ...    4.0    4.0    0.0   1.0   0.0   1.0   1.0    0.0      0.0     NaN
 207  ...    1.0    1.0    0.0   0.0   0.0   0.0   0.0    0.0      0.0     NaN
 208  ...    NaN    NaN    NaN   NaN   NaN   NaN   NaN    NaN      NaN     NaN

 [209 rows x 32 columns]]

In [43]:
url_data=pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html")

In [44]:
type(url_data)

list

In [45]:
len(url_data)

2

In [52]:
df3= url_data[0]

In [53]:
df3

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1.0,James Harden,25.0,HOU,SG,81.0,81.0,2981.0,647.0,1470.0,...,384.0,459.0,565.0,154.0,60.0,321.0,208.0,2217.0,4.0,"MVP-2,AS,NBA1"
1,2.0,Stephen Curry,26.0,GSW,PG,80.0,80.0,2613.0,653.0,1341.0,...,285.0,341.0,619.0,163.0,16.0,249.0,158.0,1900.0,0.0,"MVP-1,AS,NBA1"
2,3.0,Russell Westbrook,26.0,OKC,PG,67.0,67.0,2302.0,627.0,1471.0,...,364.0,488.0,574.0,140.0,14.0,293.0,184.0,1886.0,11.0,"MVP-4,AS,NBA2"
3,4.0,LeBron James,30.0,CLE,SF,69.0,69.0,2493.0,624.0,1279.0,...,365.0,416.0,511.0,109.0,49.0,272.0,135.0,1743.0,2.0,"MVP-3,DPOY-13,AS,NBA1"
4,5.0,Damian Lillard,24.0,POR,PG,82.0,82.0,2925.0,590.0,1360.0,...,329.0,378.0,507.0,97.0,21.0,222.0,164.0,1720.0,0.0,AS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,489.0,Malcolm Lee,24.0,PHI,SG,1.0,0.0,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
648,490.0,Kalin Lucas,25.0,MEM,PG,1.0,0.0,6.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN
649,491.0,Ronny Turiaf,32.0,MIN,C,2.0,0.0,19.0,0.0,0.0,...,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
650,492.0,David Wear,24.0,SAC,PF,2.0,0.0,7.0,0.0,2.0,...,0.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
651,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
df3.head(5)

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1.0,James Harden,25.0,HOU,SG,81.0,81.0,2981.0,647.0,1470.0,...,384.0,459.0,565.0,154.0,60.0,321.0,208.0,2217.0,4.0,"MVP-2,AS,NBA1"
1,2.0,Stephen Curry,26.0,GSW,PG,80.0,80.0,2613.0,653.0,1341.0,...,285.0,341.0,619.0,163.0,16.0,249.0,158.0,1900.0,0.0,"MVP-1,AS,NBA1"
2,3.0,Russell Westbrook,26.0,OKC,PG,67.0,67.0,2302.0,627.0,1471.0,...,364.0,488.0,574.0,140.0,14.0,293.0,184.0,1886.0,11.0,"MVP-4,AS,NBA2"
3,4.0,LeBron James,30.0,CLE,SF,69.0,69.0,2493.0,624.0,1279.0,...,365.0,416.0,511.0,109.0,49.0,272.0,135.0,1743.0,2.0,"MVP-3,DPOY-13,AS,NBA1"
4,5.0,Damian Lillard,24.0,POR,PG,82.0,82.0,2925.0,590.0,1360.0,...,329.0,378.0,507.0,97.0,21.0,222.0,164.0,1720.0,0.0,AS

In [56]:
df3.tail(4)

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
648,490.0,Kalin Lucas,25.0,MEM,PG,1.0,0.0,6.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN
649,491.0,Ronny Turiaf,32.0,MIN,C,2.0,0.0,19.0,0.0,0.0,...,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
650,492.0,David Wear,24.0,SAC,PF,2.0,0.0,7.0,0.0,2.0,...,0.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
651,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
df3.columns

Index(['Rk', 'Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Trp-Dbl', 'Awards'],
      dtype='object')

In [58]:
df3.dtypes

Rk         float64
Player      object
Age        float64
Team        object
Pos         object
G          float64
GS         float64
MP         float64
FG         float64
FGA        float64
FG%        float64
3P         float64
3PA        float64
3P%        float64
2P         float64
2PA        float64
2P%        float64
eFG%       float64
FT         float64
FTA        float64
FT%        float64
ORB        float64
DRB        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
TOV        float64
PF         float64
PTS        float64
Trp-Dbl    float64
Awards      object
dtype: object

In [60]:
df3[['Rk', 'Player', 'Age', 'Team', 'Pos', 'G', 'GS']]

        Rk             Player   Age Team  Pos     G    GS
0      1.0       James Harden  25.0  HOU   SG  81.0  81.0
1      2.0      Stephen Curry  26.0  GSW   PG  80.0  80.0
2      3.0  Russell Westbrook  26.0  OKC   PG  67.0  67.0
3      4.0       LeBron James  30.0  CLE   SF  69.0  69.0
4      5.0     Damian Lillard  24.0  POR   PG  82.0  82.0
..     ...                ...   ...  ...  ...   ...   ...
647  489.0        Malcolm Lee  24.0  PHI   SG   1.0   0.0
648  490.0        Kalin Lucas  25.0  MEM   PG   1.0   0.0
649  491.0       Ronny Turiaf  32.0  MIN    C   2.0   0.0
650  492.0         David Wear  24.0  SAC   PF   2.0   0.0
651    NaN     League Average   NaN  NaN  NaN   NaN   NaN

[652 rows x 7 columns]

In [66]:
from re import T
df3.to_csv("players_data.csv",index=False)

In [67]:
df3

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Trp-Dbl,Awards
0,1.0,James Harden,25.0,HOU,SG,81.0,81.0,2981.0,647.0,1470.0,...,384.0,459.0,565.0,154.0,60.0,321.0,208.0,2217.0,4.0,"MVP-2,AS,NBA1"
1,2.0,Stephen Curry,26.0,GSW,PG,80.0,80.0,2613.0,653.0,1341.0,...,285.0,341.0,619.0,163.0,16.0,249.0,158.0,1900.0,0.0,"MVP-1,AS,NBA1"
2,3.0,Russell Westbrook,26.0,OKC,PG,67.0,67.0,2302.0,627.0,1471.0,...,364.0,488.0,574.0,140.0,14.0,293.0,184.0,1886.0,11.0,"MVP-4,AS,NBA2"
3,4.0,LeBron James,30.0,CLE,SF,69.0,69.0,2493.0,624.0,1279.0,...,365.0,416.0,511.0,109.0,49.0,272.0,135.0,1743.0,2.0,"MVP-3,DPOY-13,AS,NBA1"
4,5.0,Damian Lillard,24.0,POR,PG,82.0,82.0,2925.0,590.0,1360.0,...,329.0,378.0,507.0,97.0,21.0,222.0,164.0,1720.0,0.0,AS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,489.0,Malcolm Lee,24.0,PHI,SG,1.0,0.0,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
648,490.0,Kalin Lucas,25.0,MEM,PG,1.0,0.0,6.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,NaN
649,491.0,Ronny Turiaf,32.0,MIN,C,2.0,0.0,19.0,0.0,0.0,...,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
650,492.0,David Wear,24.0,SAC,PF,2.0,0.0,7.0,0.0,2.0,...,0.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN
651,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

>>pandas advance

In [68]:
df=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [69]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [71]:
type(df)

pandas.core.frame.DataFrame

In [72]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [73]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

>>extracting categorical data

In [75]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [77]:
df[["Name","Sex","Ticket","Cabin","Embarked"]]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

>.filtering and Automating data

In [78]:
df.dtypes=="object"

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [80]:
df.dtypes[df.dtypes =="object"]

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [81]:
df.dtypes[df.dtypes =="object"].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [82]:
type(df.dtypes[df.dtypes =="object"])

pandas.core.series.Series

In [88]:
df[(df.dtypes[df.dtypes == "object"].index)]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [90]:
df[(df.dtypes[df.dtypes == "object"].index)].describe()

                       Name   Sex  Ticket Cabin Embarked
count                   891   891     891   204      889
unique                  891     2     681   147        3
top     Dooley, Mr. Patrick  male  347082    G6        S
freq                      1   577       7     4      644

In [91]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [92]:
df[(df.dtypes[df.dtypes == "Float"].index)]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[891 rows x 0 columns]

In [94]:
df[(df.dtypes[df.dtypes == "int64"].index)]

     PassengerId  Survived  Pclass  SibSp  Parch
0              1         0       3      1      0
1              2         1       1      1      0
2              3         1       3      0      0
3              4         1       1      1      0
4              5         0       3      0      0
..           ...       ...     ...    ...    ...
886          887         0       2      0      0
887          888         1       1      0      0
888          889         0       3      1      2
889          890         1       1      0      0
890          891         0       3      0      0

[891 rows x 5 columns]